spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://211.222.25.101:5432/ATproject4
    username: ${db.username:ATproject4}
    password: ${db.password:at1234}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true